name: rl_robots
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py38h578d9bd_2
  - fasttext=0.9.2=py38h0efe328_2
  - libblas=3.9.0=11_linux64_openblas
  - libcblas=3.9.0=11_linux64_openblas
  - libedit=3.1.20210910=h7f8727e_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=11.2.0=h69a702a_15
  - libgfortran5=11.2.0=h5c6108e_15
  - libgomp=9.3.0=h5101ec6_17
  - liblapack=3.9.0=11_linux64_openblas
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1n=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - python=3.8.0=h0371630_2
  - python_abi=3.8=2_cp38
  - readline=7.0=h7b6447c_5
  - setuptools=58.0.4=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - absl-py==1.0.0
    - ale-py==0.7.4
    - asttokens==2.0.5
    - astunparse==1.6.3
    - attrs==21.4.0
    - autorom==0.4.2
    - autorom-accept-rom-license==0.4.2
    - backcall==0.2.0
    - black==22.1.0
    - botocore==1.13.50
    - cachetools==5.0.0
    - cffi==1.15.0
    - click==8.0.3
    - cloudpickle==2.0.0
    - cycler==0.11.0
    - cython==0.29.28
    - debugpy==1.5.1
    - decorator==5.1.1
    - deprecated==1.2.13
    - dm-tree==0.1.6
    - entrypoints==0.4
    - executing==0.8.2
    - filelock==3.4.2
    - fonttools==4.29.1
    - future==0.18.2
    - gast==0.3.3
    - glfw==2.5.1
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.43.0
    - gym==0.21.0
    - gym-minigrid==1.0.2
    - h5py==2.10.0
    - hyperopt==0.2.7
    - imageio==2.14.1
    - imageio-ffmpeg==0.4.5
    - importlib-metadata==4.10.1
    - importlib-resources==5.4.0
    - ipykernel==6.8.0
    - ipython==8.0.1
    - jedi==0.18.1
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.1
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - lockfile==0.12.2
    - lz4==3.1.10
    - markdown==3.3.6
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - msgpack==1.0.3
    - mypy-extensions==0.4.3
    - nest-asyncio==1.5.4
    - networkx==2.6.3
    - numpy==1.22.1
    - oauthlib==3.2.0
    - opencv-python==4.5.5.64
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.4.0
    - parso==0.8.3
    - pathspec==0.9.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.0.0
    - platformdirs==2.4.1
    - prompt-toolkit==3.0.26
    - protobuf==3.19.4
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py4j==0.10.9.5
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.9.2
    - pybind11-global==2.6.1
    - pycparser==2.21
    - pygame==2.1.2
    - pyglet==1.5.23
    - pygments==2.11.2
    - pyhocon==0.3.59
    - pyparsing==2.4.7
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pywavelets==1.2.0
    - pyyaml==6.0
    - pyzmq==22.3.0
    - ray==1.9.2
    - redis==4.1.2
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-image==0.19.1
    - scikit-learn==1.0.2
    - scipy==1.4.1
    - setproctitle==1.2.2
    - sklearn==0.0
    - stack-data==0.1.4
    - tabulate==0.8.9
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.4.1
    - tensorflow-estimator==2.3.0
    - tensorflow-gpu==2.3.0
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - timm==0.4.12
    - tomli==2.0.0
    - torch==1.10.2
    - torchvision==0.11.3
    - tornado==6.1
    - tqdm==4.63.0
    - traitlets==5.1.1
    - typing-extensions==4.0.1
    - urllib3==1.25.11
    - wcwidth==0.2.5
    - werkzeug==2.0.2
    - wrapt==1.13.3
    - zipp==3.7.0
prefix: /home/users/grartem/anaconda3/envs/rl_robots
